### ISSUE TITLE
When sharing posts on Facebook, no inline preview is generated

### ISSUE THREAD

**Issue by simevidas** [HubPress/hubpress.io#207]
Example:

![capture](https://cloud.githubusercontent.com/assets/716405/7557720/ad541484-f796-11e4-8160-aa8cb55b2bb8.PNG)

(for [this blog post](http://www.simevidas.com/2015/05/10/Blowing-up-pixel-art-on-the-Web.html))

I’m assuming HubPress’s template needs to contain certain meta elements which are then picked up by Facebook.

**Comment by anthonny** [comment]
Hi @simevidas and thank you for filling this issue!

You're right, certain meta are required

**Comment by dgrizzla** [comment]
I was having the same Issue, and I just added an :image:: element (e.g. image::https://fronteruk.files.wordpress.com/2010/01/istock_000000260938medium3.jpg[Picture Name]) and published my post, then put it on Facebook. 

![captura](https://cloud.githubusercontent.com/assets/6843339/8509209/86ea4d70-2254-11e5-87e5-c17451d74122.PNG)

I'm not sure if this issue was already fixed but this worked for me. Hope it helps.

**Comment by ziyaddin** [comment]
@dgrizzla I did the same, works fine. :+1:

**Comment by jaredmorgs** [comment]
So posts require an image for facebook to share them properly. 🙄 

Thanks for discovering the fix. I'll document this in the Knowledgebase just in case the issue still happens.

**Comment by jaredmorgs** [comment]
https://hubpress.gitbooks.io/hubpress-knowledgebase/content/write/sharing_facebook_no_image.html now covers this issue. Let me know if you feel any more information is required.

**Comment by laposheureux** [comment]
So Facebook takes the first image on the page because the data for a specific image is not provided in open graph tags. I'd much prefer if Hubpress could put the image defined by :hp-image: into the head as an actual open graph tag URL so the intended header image can always show up (the theme I'm using sets it as a background image which Facebook ignores)

**Comment by laposheureux** [comment]
It seems the behavior improves over time once Facebook spends more time crawling the site. When I go and force their open graph debugger to re-crawl a page or the whole site, my immediate results improve afterward. Explicitly setting the og:image tag would be helpful to improve this behavior.
