### ISSUE TITLE
CNAME addition breaks admin

### ISSUE THREAD

**Issue by ssundarraj** [HubPress/hubpress.io#244]
When I add a CNAME it doesn't save, and it doesn't open the admin panel.

**Comment by anthonny** [comment]
Hi @ssundarraj!

I can't find your fork of HubPress

**Comment by ssundarraj** [comment]
I deleted my fork of hubpress. This issue occurred multiple times. I can reproduce the error for you if you want me to.

**Comment by anthonny** [comment]
Yes if you have a moment to reproduce, i could understand what happen

**Comment by ssundarraj** [comment]
http://github.com/ssundarraj/hubpress.io

**Comment by anthonny** [comment]
Ok i understand the problem.
You use a CNAME for your repository `ssundarraj.github.io` => ssundarraj.me

So for your instance of HubPress, you do not have to define a CNAME because by default your instance is available at `http://ssundarraj.me/hubpress.io`

The problem is for the link, without the CNAME the links in HubPress are `https://ssundarraj.github.io/hubpress.io` 
I will add a property in the config to force the URL 

Thank you for your help

**Comment by ssundarraj** [comment]
:+1:

**Comment by wols** [comment]
Is the fix available? Please help!

**Comment by anthonny** [comment]
@wols not yet sorry

**Comment by wols** [comment]
A messy workaround:
```
git pull
git mv CNAME CNAME.tmp
git commit -m "hidden CNAME"
git push
```
http://ssundarraj.me/ gives 404
http://ssundarraj.github.io/blog/hubpress works
```
git pull
git mv CNAME.tmp CNAME
git commit -m "add CNAME"
git push
```
http://ssundarraj.me/ works again

**Comment by jaredmorgs** [comment]
Appears to be a valid bug still @anthonny 

I won't close this one off unless you overrule the decision.
