### ISSUE TITLE
Error posts URLs.

### ISSUE THREAD

**Issue by Cansll** [HubPress/hubpress.io#515]
I've just forked hubpress and configured 'config.json' Then I've changed default branch and bound my custom domain, and then I pushed a post. But when I try to open my post, it tells my Error 404. I found that my post's link is not valid. (missing a "/" like "www.ckylin-mc.cn2017-8-11-hello-hubpress.adoc/" )
My custom domain: www.ckylin-mc.cn
My repo: https://github.com/Cansll/blog

Sorry for my poor English.

![image](https://user-images.githubusercontent.com/11648014/29214551-5e2f4b08-7eda-11e7-84ed-0d4eface2617.png)

**Comment by anthonny** [comment]
Hi @Cansll,
Could you try with this date please: 
```
:published_at: 2017-8-11
```

There is not enough validation on this field

**Comment by Cansll** [comment]
@anthonny I'm sure I have already done this. 
![image](https://user-images.githubusercontent.com/11648014/29218032-148a483e-7ee6-11e7-92d4-2cc2774aab27.png)
![image](https://user-images.githubusercontent.com/11648014/29218060-288e86e2-7ee6-11e7-87db-9ebffbee3420.png)

**Comment by anthonny** [comment]
Oh sorry my bad:

```
:published_at: 2017-08-11
```

**Comment by Cansll** [comment]
I don't know what's the difference but when I have done this my post is disappeared.

![image](https://user-images.githubusercontent.com/11648014/29218389-4859fb90-7ee7-11e7-84fe-43b245e606d3.png)

**Comment by Cansll** [comment]
![image](https://user-images.githubusercontent.com/11648014/29218708-3ac7a99a-7ee8-11e7-84cd-c4454c0cdd97.png)

**Comment by anthonny** [comment]
Yes the "422" is a referenced bug, could you refresh your page and publish again please.

**Comment by anthonny** [comment]
I'm sorry it a bit complicated :/

**Comment by Cansll** [comment]
Again...
![image](https://user-images.githubusercontent.com/11648014/29218833-b47dbd7e-7ee8-11e7-83b2-50ef0b622039.png)

**Comment by Cansll** [comment]
@anthonny so what should I do?

**Comment by anthonny** [comment]
Could go to the posts list and click on the sync button? Then retry please

**Comment by Cansll** [comment]
I have tried and it not works...Infinite loading...and my post has now changed to a draft...

**Comment by anthonny** [comment]
I will try to release the version that should fix the error 422. Maybe tonight or tomorrow, could you wait until this new version please?

**Comment by Cansll** [comment]
OK :)

**Comment by anthonny** [comment]
Hi here, the 0.8.1 is out, ould you upgrade your instance and tell me if now everything is ok please?

**Comment by Cansll** [comment]
Ok I'll try.

**Comment by Cansll** [comment]
I can push my posts now, but the wrong post link is still not fixed. 
![image](https://user-images.githubusercontent.com/11648014/29393446-48c77988-8336-11e7-9db8-96161e1e5eb5.png)
It seems missing a "/"...

**Comment by Cansll** [comment]
I mean it may should be more like "www.ckylin-mc.cn/xxx" but not "www.ckylin-mc.cnxxx"...

**Comment by Cansll** [comment]
![image](https://user-images.githubusercontent.com/11648014/29393739-36053018-8338-11e7-9b6d-bbfe9e44b5a8.png)

I see your repo(https://github.com/HubPress/blog.hubpress.io). Posts should be archived by date. **But I can't find any archive folder in my repo**. I just can found my posts in _posts and root folder. And they all ".adoc" format, not ".html".

**Comment by anthonny** [comment]
@Cansll like i said here https://github.com/HubPress/hubpress.io/issues/515#issuecomment-321832341, you must use a `:published_at:` with the format YYYY-MM-DD

With that it should be ok ;)

**Comment by Cansll** [comment]
@anthonny Wow thanks! (I finally found that it's my mistake haha! "2017-**8**-11" and "2017-**08**-11")

**Comment by anthonny** [comment]
Awesome! Thank you so much for having been so patient

**Comment by Cansll** [comment]
Sorry, but the "422 bug" appeared again.
I try to publish my post and then fall into infinite loading...
I try to refresh and republish it but the "Publish post" button has changed to "Unpublish post" button, no post is generated and published.

Can you add some error handler, sometimes it falls into infinite loading but I don't know what is happening then wait and wait until I found errors in chrome console...
